package com.hoanganhtuan01101995.sdk.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final VideoDao videoDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        videoDao = new VideoDao(videoDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(Video.class, videoDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        videoDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
