package com.hoanganhtuan01101995.sdk.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "VIDEO".
 */
public class VideoDao extends AbstractDao<Video, String> {

    public static final String TABLENAME = "VIDEO";

    /**
     * Properties of entity Video.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property VideoId = new Property(0, String.class, "videoId", true, "VIDEO_ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property PublishedAt = new Property(3, Long.class, "publishedAt", false, "PUBLISHED_AT");
    }


    public VideoDao(DaoConfig config) {
        super(config);
    }

    public VideoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIDEO\" (" + //
                "\"VIDEO_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: videoId
                "\"TITLE\" TEXT," + // 1: title
                "\"DESCRIPTION\" TEXT," + // 2: description
                "\"PUBLISHED_AT\" INTEGER);"); // 4: publishedAt
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIDEO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Video entity) {
        stmt.clearBindings();

        String videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindString(1, videoId);
        }

        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }

        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }

        Long publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindLong(4, publishedAt);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Video entity) {
        stmt.clearBindings();

        String videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindString(1, videoId);
        }

        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }

        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }

        Long publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindLong(4, publishedAt);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }

    @Override
    public Video readEntity(Cursor cursor, int offset) {
        Video entity = new Video( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // videoId
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
                cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // publishedAt
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Video entity, int offset) {
        entity.setVideoId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPublishedAt(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
    }

    @Override
    protected final String updateKeyAfterInsert(Video entity, long rowId) {
        return entity.getVideoId();
    }

    @Override
    public String getKey(Video entity) {
        if (entity != null) {
            return entity.getVideoId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Video entity) {
        return entity.getVideoId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
